version: 2
updates:
  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "gitsubmodule"
    directory: "/"
    schedule:
      interval: "daily"
  - package-ecosystem: "npm"
    directory: "/site/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/data/"
    schedule:
      interval: "daily"
  - package-ecosystem: "docker"
    directory: "/docker/planetiler/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "maven"
  - package-ecosystem: "docker"
    directory: "/dependencies/"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "maven"
