services:
  web:
    image: ghcr.io/cmahnke/projektemacher-maps/web:dev
    build:
      dockerfile: ./docker/web/Dockerfile.dev
      context: .
    ports:
      - "5173:5173"
      - "3010:3010"
    volumes:
      - type: bind
        source: ./site/viewer
        target: /tmp/build/viewer
    depends_on:
      - data
    command: ["yarn", "run", "vite", "viewer", "--debug", "--host"]

  data:
    image: ghcr.io/cmahnke/projektemacher-maps:latest
    build:
      dockerfile: ./docker/data/Dockerfile
      context: .
    volumes:
      - "./conf/default.conf:/etc/nginx/conf.d/default.conf:ro"
    ports:
      - "8080:80"
