services:
  web:
    image: ghcr.io/cmahnke/projektemacher-maps/web:dev
    build:
      dockerfile: ./docker/web/Dockerfile.dev
      context: .
    ports:
      - "5173:5173"
    volumes:
      - "./site/:/tmp/build/:rw"
    depends_on:
      - data
  data:
    image: ghcr.io/cmahnke/projektemacher-maps:latest
    build:
      dockerfile: ./docker/data/Dockerfile
      context: .
    ports:
      - "8080:80"
