# syntax=docker/dockerfile:experimental

FROM ghcr.io/cmahnke/projektemacher-maps/planetiler:latest

LABEL maintainer="cmahnke@gmail.com"
LABEL org.opencontainers.image.source https://github.com/cmahnke/map-tools

ENV BUILD_DEPS="wget" \
    BUILD_DIR=/tmp/build

RUN apk --update upgrade && \
    apk add --no-cache $RUN_DEPS && \
    mkdir -p $BUILD_DIR/data/sources/  && \
    cd $BUILD_DIR/data/sources/ && \
    wget https://osmdata.openstreetmap.de/download/water-polygons-split-3857.zip && \
    wget https://dev.maptiler.download/geodata/omt/lake_centerline.shp.zip && \
    wget https://dev.maptiler.download/geodata/omt/natural_earth_vector.sqlite.zip && \
## Cleanup
    cd / && \
    apk del $BUILD_DEPS && \
    rm -rf /var/cache/apk/*

WORKDIR $BUILD_DIR
