# syntax=docker/dockerfile:experimental

FROM node:20-alpine as builder

LABEL maintainer="cmahnke@gmail.com"
LABEL org.opencontainers.image.source https://github.com/cmahnke/map-data

ENV BUILD_DIR=/tmp/build

COPY conf/default.conf /etc/nginx/conf.d/

RUN --mount=target=/mnt/build-context \
    mkdir -p $BUILD_DIR && \
    cd $BUILD_DIR && \
    npm install --global esbuild-wasm && \
    cp -ra /mnt/build-context/site/. $BUILD_DIR && \
    cd $BUILD_DIR && \
    yarn install && \
    yarn run build

WORKDIR $BUILD_DIR

CMD ["yarn", "run", "vite", "viewer", "--debug", "--host"]
