# syntax=docker/dockerfile:experimental

FROM node:22-alpine as builder

LABEL maintainer="cmahnke@gmail.com"
LABEL org.opencontainers.image.source https://github.com/cmahnke/map-data

ENV WEB_ROOT=/usr/share/nginx/html/

COPY conf/default.conf /etc/nginx/conf.d/

RUN --mount=target=/mnt/build-context \
    mkdir -p $WEB_ROOT && \
    cd $WEB_ROOT && \
    npm install --global esbuild-wasm && \
    cp -ra /mnt/build-context/site/. $WEB_ROOT && \
    cd $WEB_ROOT && \
    yarn install && \
    yarn run --mode=development 

WORKDIR $WEB_ROOT

CMD ["yarn", "run", "vite", "viewer", "--debug", "--host", "--mode=development"]
