name: Publish Maps

on:
  workflow_run:
    workflows: ["Publish Docker images"]
    branches: [main]
    types:
      - completed
  schedule:
    - cron: '30 4 * * 2'
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-22.04
    steps:
      - name: Free some disk space
        run: |
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL

      - uses: actions/checkout@v4
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)

      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.2.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false

      - name: Setup deploy env
        env:
          DEPLOY_SSH_IDENTITY: ${{ secrets.DEPLOY_SSH_IDENTITY }}
        run: |
          mkdir -p ~/.ssh && echo "$DEPLOY_SSH_IDENTITY" >>  ~/.ssh/known_hosts

      - name: Extract Frontend
        run: |
          mkdir -p ./docs/
          docker pull ghcr.io/cmahnke/projektemacher-maps/viewer:latest
          docker create --name viewer ghcr.io/cmahnke/projektemacher-maps/viewer:latest
          docker cp viewer:/usr/share/nginx/html/. ./docs/
          docker rm -f viewer
          docker rmi ghcr.io/cmahnke/projektemacher-maps/viewer:latest

      - name: Extract central Europe
        run: |
          mkdir -p ./docs/central-europe/
          docker pull ghcr.io/cmahnke/map-data/central-europe:latest
          docker create --name central-europe ghcr.io/cmahnke/map-data/central-europe:latest
          docker cp central-europe:/data/. ./docs/central-europe/
          docker rm -f central-europe
          docker rmi ghcr.io/cmahnke/map-data/central-europe:latest

      - name: Extract small datasets
        run: |
          mkdir -p ./docs/goettingen/ ./docs/sylt/
          docker pull ghcr.io/cmahnke/map-data/goettingen:latest
          docker create --name goettingen ghcr.io/cmahnke/map-data/goettingen:latest
          docker cp goettingen:/data/. ./docs/goettingen/
          docker rm -f goettingen
          docker rmi ghcr.io/cmahnke/map-data/goettingen:latest

          docker pull ghcr.io/cmahnke/map-data/sylt:latest
          docker create --name sylt ghcr.io/cmahnke/map-data/sylt:latest
          docker cp sylt:/data/. ./docs/sylt/
          docker rm -f sylt
          docker rmi ghcr.io/cmahnke/map-data/sylt:latest

      - name: Add config
        run: |
          cp conf/.htaccess ./docs/central-europe
          cp conf/.htaccess ./docs/goettingen
          cp conf/.htaccess ./docs/sylt

      - name: Map directory upload and cleanup
        env:
          DEPLOY_SERVER: ${{ secrets.DEPLOY_SERVER }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          SSHPASS: ${{ secrets.DEPLOY_PASS }}
          DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        run: |
          cd docs
          sshpass -e rsync -a --info=progress2 --size-only --delete --relative . $DEPLOY_USER@$DEPLOY_SERVER:$DEPLOY_PATH/projektemacher.org/maps/
