name: Publish Docker images

permissions:
  packages: write

on:
  push:
    branches:
      - main

jobs:

  build_maps_viewer:
    name: Push conversion-tools Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.0.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.CR_PAT }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.0.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v5.0.0
        with:
          push: true
          context: .
          file: docker/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/projektemacher-maps/central-europe:latest
      - name: Extract
        run: |
          mkdir -p ./docs/
          docker pull ghcr.io/cmahnke/projektemacher-maps/central-europe:latest
          docker create --name web ghcr.io/cmahnke/projektemacher-maps/central-europe:latest
          docker cp web:/usr/share/nginx/html/* ./docs/
          docker rm -f web
          docker rmi ghcr.io/cmahnke/projektemacher-maps/central-europe:latest
      - name: Deploy site
        uses: peaceiris/actions-gh-pages@v3.9.3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs
          force_orphan: true
