name: Publish Docker images

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write

jobs:
  build_maps_data:
    name: Push Map Data Docker image to GitHub Packages
    runs-on: ubuntu-latest
    needs: [build_maps_viewer]
    steps:
      - name: Free some disk space
        run: |
          df -h
          sudo apt-get update
          sudo apt-get remove -y '^dotnet-.*' '^llvm-.*' 'php.*' '^mongodb-.*' '^mysql-.*' '^postgresql-.*' '^gfortran-.*' '^cmake-.*' '^aspnetcore-.*' azure-cli google-chrome-stable firefox powershell
          sudo rm -rf /usr/local/lib/android /opt/ghc /opt/hostedtoolcache/CodeQL /usr/local/graalvm/ /usr/local/share/powershell /usr/local/lib/android /usr/local/lib/node_modules /usr/local/.ghcup/ /usr/share/dotnet/
          sudo apt-get autoremove -y
          sudo apt-get clean
          sudo rm -rf /var/lib/apt/lists/*
          docker rmi -f node:14 node:16 node:18 node:14-alpine node:16-alpine node:18-alpine ubuntu:18.04 ubuntu:20.04 ubuntu:22.04 debian:10 debian:11 buildpack-deps:buster buildpack-deps:bullseye
          df -h

      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.0
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: docker/data/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/projektemacher-maps:latest

  build_maps_viewer:
    name: Push Map Viewer Docker image to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.4.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.11.0
      - name: Push Viewer to GitHub Packages
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: docker/web/Dockerfile
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/projektemacher-maps/viewer:latest
      - name: Push Dev Viewer to GitHub Packages
        uses: docker/build-push-action@v6.18.0
        with:
          push: true
          context: .
          file: docker/web/Dockerfile.dev
          platforms: linux/amd64,linux/arm64
          tags: |
            ghcr.io/cmahnke/projektemacher-maps/viewer:dev
