name: Publish Tool arctifacts

on:
  push:
    branches:
      - main
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  packages: write
  contents: write

env:
  PLANTILER_OPENMAPTILES_VERSION: 3.15.0

jobs:
  build_planetiler_openmaptiles:
    name: Push Maven dependency to GitHub Packages
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v3.3.0
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          logout: false
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3.7.1
      - name: Push to GitHub Packages
        uses: docker/build-push-action@v6.9.0
        with:
          push: true
          context: .
          file: dependencies/Dockerfile
          tags: |
            ghcr.io/cmahnke/projektemacher-maps/planetiler-openmaptiles:latest
      - name: Extract
        run: |
          mkdir -p ./docs/central-europe/ ./docs/goettingen/ ./docs/sylt/
          docker create --name planetiler-openmaptiles ghcr.io/cmahnke/projektemacher-maps/planetiler-openmaptiles:latest
          docker cp planetiler-openmaptiles:/opt/planetiler/. .
          docker rm -f planetiler-openmaptiles
          docker rmi ghcr.io/cmahnke/projektemacher-maps/planetiler-openmaptiles:latest
      - name: Set Maven repository
        uses: whelk-io/maven-settings-xml-action@v22
        with:
          repositories: |
            [
              {
                "id": "central",
                "name": "Maven Central",
                "url": "https://repo1.maven.org/maven2",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "false"
                }
              },
              {
                "id": "github",
                "url": "https://maven.pkg.github.com/cmahnke/projektemacher-maps",
                "releases": {
                  "enabled": "true"
                },
                "snapshots": {
                  "enabled": "true"
                }
              }
            ]
          servers: '[{ "id": "github", "username": "${env.GITHUB_ACTOR}", "password": "${env.GITHUB_TOKEN}" }]'

      - uses: actions/delete-package-versions@v5
        continue-on-error: true
        with:
          package-name: org.openmaptiles.planetiler-openmaptiles
          package-type: maven
          min-versions-to-keep: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Deploy to Maven repository
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mvn org.apache.maven.plugins:maven-deploy-plugin:3.1.1:deploy-file \
            -DrepositoryId=github -Dfile=planetiler-openmaptiles/3.15.0-SNAPSHOT/planetiler-openmaptiles-3.15.0-SNAPSHOT.jar -DgroupId=org.openmaptiles \
            -Durl=https://maven.pkg.github.com/cmahnke/projektemacher-maps \
            -DartifactId=planetiler-openmaptiles -Dversion=3.15.0-SNAPSHOT -Dpackaging=jar
